# Generated by Django 4.1.3 on 2022-12-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dificultad',
                'verbose_name_plural': 'Dificultadws',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dificultad')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.TextField()),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('correcta', models.BooleanField()),
                ('texto', models.TextField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test'),
        ),
    ]
